<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>HomeDiary_api</RootNamespace>
    <UserSecretsId>homediary-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="AWSSDK.SimpleEmailV2" Version="4.0.102.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="MimeKit" Version="4.17.0" />
    <PackageReference Include="PdfPig" Version="0.1.15" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="../home-diary-app/src/assets/images/title-bar-app-name.png"
             Link="EmailAssets/title-bar-app-name.png"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
